CATEGORY_DROPDOWN = "category-dropdown"
SELECT_ALL_CATEGORIES_BUTTON = "select-all-categories-button"
BAR_GRAPH = "bar-graph"
YEAR_DROPDOWN = "year-dropdown"
SELECT_ALL_YEARS_BUTTON = "select-all-years-button"